CONTENTS_LIST = [
    ("Python Introduction", "python"),
    ("Python Installation", "python"),
    ("Python Syntax", "python"),
    ("Python Variables", "python"),
    ("Python Comments", "python"),
    ("Python Strings", "python"),
    ("Python Numbers", "python"),
    ("Python Type Casting", "python"),
    ("Python Booleans", "python"),
    ("Python Operators", "python"),
    ("Python Lists", "python"),
    ("Python Sets", "python"),
    ("Python Dictionaries", "python"),
    ("Python Conditional Statements", "python"),
    ("Python Functions", "python"),
    ("Python Scopes", "python"),
    ("Python PIP", "python"),
    ("Python Modules", "python"),
    ("Python Classes & Objects", "python"),
    ("Python Inheritance", "python"),
    ("Python Exception Handling", "python"),
    ("Python File Handling ", "python"),
    ("Python Iterators", "python"),
    ("Python Decorators", "python"),
    ("Python Lambda functions", "python"),
    ("Python Maths", "python"),
    ("Python Dates", "python"),
    ("Python Inputs", "python"),
    ("Python String Formatting", "python"),
    ("Python Virtual environments", "python"),
    ("Python logging", "python"),
    ("Python Json", "python"),
    ("JS Introduction", "javascript"),
    ("Add JS", "javascript"),
    ("JS Output", "javascript"),
    ("JS Statements", "javascript"),
    ("JS Syntax", "javascript"),
    ("JS Comments", "javascript"),
    ("JS Variables", "javascript"),
    ("JS Data types", "javascript"),
    ("JS Operators", "javascript"),
    ("JS Functions", "javascript"),
    ("JS Events", "javascript"),
    ("JS Strings", "javascript"),
    ("JS String Methods", "javascript"),
    ("JS Array", "javascript"),
    ("JS Objects", "javascript"),
]

CONTENTS_PAGE = [
    (
        "What is Python?",
        "Python is a popular programming language. It was created by Guido van Rossum, and released in 1991.It is used for: web development (server-side),software development,mathematics,system scripting.",
        "Python Introduction",
    ),
    (
        "What Can Python Do?",
        "Python can be used on a server to create web applications.Python can be used alongside software to create workflows.Python can connect to database systems. It can also read and modify files.Python can be used to handle big data and perform complex mathematics.Python can be used for rapid prototyping, or for production-ready software development.",
        "Python Introduction",
    ),
    (
        "Why Python?",
        "Python works on different platforms (Windows, Mac, Linux, Raspberry Pi, etc).Python has a simple syntax similar to the English language.Python has syntax that allows developers to write programs with fewer lines than some other programming languages.Python runs on an interpreter system, meaning that code can be executed as soon as it is written. This means that prototyping can be very quick.Python can be treated in a procedural way, an object-oriented way or a functional way.",
        "Python Introduction",
    ),
    
    (
        "Good to know",
        "The most recent major version of Python is Python 3, which we shall be using in this tutorial. However, Python 2, although not being updated with anything other than security updates, is still quite popular.In this tutorial Python will be written in a text editor. It is possible to write Python in an Integrated Development Environment, such as Thonny, Pycharm, Netbeans or Eclipse which are particularly useful when managing larger collections of Python files.",
        "Python Introduction",
    ),
    (
        "Python Syntax compared to other programming languages",
        "Python was designed for readability, and has some similarities to the English language with influence from mathematics.Python uses new lines to complete a command, as opposed to other programming languages which often use semicolons or parentheses.Python relies on indentation, using whitespace, to define scope; such as the scope of loops, functions and classes. Other programming languages often use curly-brackets for this purpose.",
        "Python Introduction",
    ),
    (
        "Example",
        "print('Hello, World!')",
        "Python Introduction",
    ),
    (
        "Install Python",
        "Many PCs and Macs will have python already installed.To check if you have python installed on a Windows PC, search in the start bar for Python or run the following on the Command Line (cmd.exe):",
        "Python Installation",
    ),
    (
        "Install Python",
        "Many PCs and Macs will have python already installed.To check if you have python installed on a Windows PC, search in the start bar for Python or run the following on the Command Line (cmd.exe):",
        "Python Installation",
    ),
    (
        "Install Python",
        "Many PCs and Macs will have python already installed.To check if you have python installed on a Windows PC, search in the start bar for Python or run the following on the Command Line (cmd.exe):",
        "Python Installation",
    ),
    (
        "Install Python",
        "Many PCs and Macs will have python already installed.To check if you have python installed on a Windows PC, search in the start bar for Python or run the following on the Command Line (cmd.exe):",
        "Python Installation",
    ),
    (
        "Install Python",
        "Many PCs and Macs will have python already installed.To check if you have python installed on a Windows PC, search in the start bar for Python or run the following on the Command Line (cmd.exe):",
        "Python Installation",
    ),
]

